version: "3.9"
volumes:
  db-data:
  bundle:
services:
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid &&
                      bundle config set --local path .bundle/vendor && bundle install &&
                      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/webapp:cached
      - bundle:/webapp/.bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  nginx:
    image: nginx:1.21
    volumes:
      - .:/webapp:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '3080:80'
    depends_on:
      - web